version: '3'

services:
  db:
    image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USER: postgresql
      POSTGRESQL_DATABASE: aerogear_mobile_metrics
  influx:
    image: influxdb
    ports:
      - "8086:8086"
  api:
    build:
      context: .
      args:
        BINARY: ./dist/linux_amd64/aerogear-app-metrics
    environment:
      PGHOST: db
      PGUSER: postgresql
      PGPASSWORD: postgres
      PGDATABASE: aerogear_mobile_metrics
    ports:
      - "3000:3000"
    depends_on:
      - db
