[[constraint]]
  name = "github.com/darahayes/go-boom"
  version = "1.0.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
